import { PartoAdequado } from '../../../models/partoAdequado'

export async function buildPartoAdequado(item: any): Promise<PartoAdequado> {
  const partoAdequado = new PartoAdequado()
  partoAdequado.setAntecedentesObstreticos(item.CD_ANT_OBSTETRICOS)
  partoAdequado.setNumeroCesareasAnteriores(item.NR_CESAREAS_ANT)
  partoAdequado.setApresentacaoFetalRn1(item.CD_RN1)
  partoAdequado.setApresentacaoFetalRn2(item.CD_RN2)
  partoAdequado.setApresentacaoFetalRn3(item.CD_RN3)
  partoAdequado.setApresentacaoFetalRn4(item.CD_RN4)
  partoAdequado.setApresentacaoFetalRn5(item.CD_RN5)
  partoAdequado.setInicioTrabalhoParte(item.CD_INICIO_PARTO)
  partoAdequado.setRupturaUterina(item.IE_RUPTURA_UTERINA)
  partoAdequado.setLaceracaoPerineal(item.IE_LACERACAO_PERINEAL)
  partoAdequado.setTransfusaoSanguinea(item.IE_TRANSFUSAO_SANGUINEA)
  partoAdequado.setMorteMaterna(item.IE_MORTE_MATERNA)
  partoAdequado.setMorteFetalIntraparto(item.IE_MORTE_FETAL)
  partoAdequado.setAdmissaoMaternaUti(item.IE_ADM_MATERNA)
  partoAdequado.setRetornoSalaParto(item.IE_RETORNO_PARTO)
  partoAdequado.setIndiceSatisfacaoHospital(item.QT_SATISFACAO_HOSP)
  partoAdequado.setIndiceSatisfacaoEquipe(item.QT_SATISFACAO_EQUIPE)
  partoAdequado.setHouveContatoPele(item.IE_CONTATO_PELE)
  partoAdequado.setPosicaoParto(item.CD_POSICAO_PARTO)
  partoAdequado.setMedicacaoInducaoParto(item.IE_MEDICACAO_INDUCAO)
  partoAdequado.setUsoOcitocinaMisoprostol(item.CD_OCITOCINA)
  partoAdequado.setParturienteAcompanhada(item.IE_PARTURIENTE_ACOMP)
  partoAdequado.setPresencaDoula(item.IE_DOULA)
  partoAdequado.setRealizadaEpisiotomia(item.IE_EPISIOTOMIA)
  partoAdequado.setHouveAleitamentoMaterno(item.IE_ALEITAMENTO)
  partoAdequado.setQuandoOcorreuClampeamento(item.CD_CLAMPEAMENTO)
  partoAdequado.setHouveAleitamentoMaterno(item.IE_ANALGESIA)
  partoAdequado.setMetodoAnalgesia(item.IE_ANALGESIA)
  partoAdequado.setPerimetroCefalicoRn1(item.QT_PER_CEF_RN1)
  partoAdequado.setPerimetroCefalicoRn2(item.QT_PER_CEF_RN2)
  partoAdequado.setPerimetroCefalicoRn3(item.QT_PER_CEF_RN3)
  partoAdequado.setPerimetroCefalicoRn4(item.QT_PER_CEF_RN4)
  partoAdequado.setPerimetroCefalicoRn5(item.QT_PER_CEF_RN5)
  partoAdequado.setCesariana(item.CD_MOT_CESARIANA)
  partoAdequado.setNumeroCesareasAnteriores(item.NR_PAR_NAT_ANT)
  return partoAdequado
}
